### PR TITLE
Add wrap files for tclap-1.2.3

### PR DESCRIPTION
**Pull request by ManuelAtWork**
Here are the files for tclap-1.2.3. (Some changes to the unit tests.)

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Can we please just skip straight to 1.2.4? I'm not sure what the point of uploading a bunch of releases from, as it turns out, 2011-2017 is, but the usual mesonwrap policy is to keep existing wraps around but only publish new ones if they're the latest version. Because people should probably, when newly introducing the software to their project, focus on using the latest version.

Unless there is some reason you specifically need old versions?

**Comment by ManuelAtWork** [comment]
Oh, sorry, I was not aware of that policy.

Maybe, someone who is migrating to Meson wants to keep dependencies as they are. (Me, for example, in many cases.) As I am going through the changes version-by-version anyway, making wraps along the way is not a big deal for me. But I will stop that practice if it creates major effort on your side.

**Comment by eli-schwartz** [comment]
It's not really a huge deal, but some effort is slightly more than no effort and... it's something we don't really expect to be used.

In the past, we've just accepted on faith if someone says they have a desire to use the old version, and accepted that old version. But we tend to not accept older versions than the latest if they're submitted "for the sake of having a complete list of versions" but without a definite use case.

**Comment by ManuelAtWork** [comment]
Okay, there is no immediate need to have a wrap for 1.2.3. The decision whether to merge this request is up to you. Sorry for the inconvenience.

In the future I will submit wraps only for versions that we use. (Some older ones may be among them, too.)

**Comment by jpakkane** [comment]
As 1.2.4 is in, I'm closing this as unnecessary.

**Pull request closed without merging**
